/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // CarbonLens Minimal Noir Color Palette
        // From total.html design system
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c7c8',
        'outline': '#8e9192',
        'outline-variant': '#444748',
        'primary': '#ffffff',
        'on-primary': '#2f3131',
        'primary-container': '#e2e2e2',
        'on-primary-container': '#636565',
        'secondary': '#c7c6c6',
        'on-secondary': '#2f3131',
        'secondary-container': '#484949',
        'on-secondary-container': '#b8b8b8',
        'tertiary': '#ffffff',
        'on-tertiary': '#303031',
        'tertiary-container': '#e4e2e2',
        'on-tertiary-container': '#646464',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
        
        // Additional theme colors from total.html
        'canvas-base': '#0B0B0B',
        'surface-primary': '#141414',
        'surface-secondary': '#1E1E1E',
        'surface-translucent-low': 'rgba(255, 255, 255, 0.03)',
        'surface-translucent-high': 'rgba(255, 255, 255, 0.06)',
      },
      fontFamily: {
        'geist': ['Geist', 'system-ui', 'sans-serif'],
        'sans': ['Geist', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      fontSize: {
        // From total.html typography scale
        'display-hero': ['80px', { lineHeight: '84px', letterSpacing: '-0.04em', fontWeight: '600' }],
        'display-hero-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-xl': ['44px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '26px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
        'eyebrow-tag': ['11px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '-0.005em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'metric-large': ['56px', { lineHeight: '60px', letterSpacing: '-0.04em', fontWeight: '600' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '1.5rem',
        'gutter-sm': '1rem',
        'margin': '2.5rem',
        'margin-sm': '1.25rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      backdropBlur: {
        'xs': '2px',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 0, 0, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.06)',
        'card': '0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
        'elevated': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [],
}